//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataContractRequestExtension", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterTipoMensagemReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterTipoAtributosReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterDadosLogReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.InclusaoLogReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ManutPlataformaReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ManutAtributoReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ManutTipoMensagemReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterPlataformaReq))]
    public partial class DataContractRequestExtension : object
    {

        private LogService.RequestExtension ExtensionField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LogService.RequestExtension Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RequestExtension", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class RequestExtension : object
    {

        private string TokenField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterTipoMensagemReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoMensagemReq : LogService.DataContractRequestExtension
    {

        private string DsTipoMensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DsTipoMensagem
        {
            get
            {
                return this.DsTipoMensagemField;
            }
            set
            {
                this.DsTipoMensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterTipoAtributosReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoAtributosReq : LogService.DataContractRequestExtension
    {

        private string DsTipoAtributoField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DsTipoAtributo
        {
            get
            {
                return this.DsTipoAtributoField;
            }
            set
            {
                this.DsTipoAtributoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterDadosLogReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterDadosLogReq : LogService.DataContractRequestExtension
    {

        private string DsFonteField;

        private string DsWcfServicoField;

        private long IdPlataformaField;

        private LogService.TipoMensagemConsulta TipoMensagemField;

        private System.Nullable<long> IdTipoAtributoField;

        private string ValAtributoField;

        private string DsUsuarioField;

        private System.DateTime DtInicioPesquisaField;

        private System.DateTime DtFimPesquisaField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DsFonte
        {
            get
            {
                return this.DsFonteField;
            }
            set
            {
                this.DsFonteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DsWcfServico
        {
            get
            {
                return this.DsWcfServicoField;
            }
            set
            {
                this.DsWcfServicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long IdPlataforma
        {
            get
            {
                return this.IdPlataformaField;
            }
            set
            {
                this.IdPlataformaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public LogService.TipoMensagemConsulta TipoMensagem
        {
            get
            {
                return this.TipoMensagemField;
            }
            set
            {
                this.TipoMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public System.Nullable<long> IdTipoAtributo
        {
            get
            {
                return this.IdTipoAtributoField;
            }
            set
            {
                this.IdTipoAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string ValAtributo
        {
            get
            {
                return this.ValAtributoField;
            }
            set
            {
                this.ValAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string DsUsuario
        {
            get
            {
                return this.DsUsuarioField;
            }
            set
            {
                this.DsUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public System.DateTime DtInicioPesquisa
        {
            get
            {
                return this.DtInicioPesquisaField;
            }
            set
            {
                this.DtInicioPesquisaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public System.DateTime DtFimPesquisa
        {
            get
            {
                return this.DtFimPesquisaField;
            }
            set
            {
                this.DtFimPesquisaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InclusaoLogReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class InclusaoLogReq : LogService.DataContractRequestExtension
    {

        private string DsMensagemField;

        private string DsFonteField;

        private string DsPilhaMensagemField;

        private string DsWCFServicoField;

        private string DsPlataformaField;

        private LogService.TipoMensagem IdTipoMensagemField;

        private string DsTipoAtributoField;

        private string DsValorAtributoField;

        private string DsUsuarioField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DsMensagem
        {
            get
            {
                return this.DsMensagemField;
            }
            set
            {
                this.DsMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string DsFonte
        {
            get
            {
                return this.DsFonteField;
            }
            set
            {
                this.DsFonteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string DsPilhaMensagem
        {
            get
            {
                return this.DsPilhaMensagemField;
            }
            set
            {
                this.DsPilhaMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string DsWCFServico
        {
            get
            {
                return this.DsWCFServicoField;
            }
            set
            {
                this.DsWCFServicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string DsPlataforma
        {
            get
            {
                return this.DsPlataformaField;
            }
            set
            {
                this.DsPlataformaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public LogService.TipoMensagem IdTipoMensagem
        {
            get
            {
                return this.IdTipoMensagemField;
            }
            set
            {
                this.IdTipoMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string DsTipoAtributo
        {
            get
            {
                return this.DsTipoAtributoField;
            }
            set
            {
                this.DsTipoAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string DsValorAtributo
        {
            get
            {
                return this.DsValorAtributoField;
            }
            set
            {
                this.DsValorAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string DsUsuario
        {
            get
            {
                return this.DsUsuarioField;
            }
            set
            {
                this.DsUsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutPlataformaReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutPlataformaReq : LogService.DataContractRequestExtension
    {

        private System.Nullable<long> IdPlataformaField;

        private string DsPlataformaField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Nullable<long> IdPlataforma
        {
            get
            {
                return this.IdPlataformaField;
            }
            set
            {
                this.IdPlataformaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string DsPlataforma
        {
            get
            {
                return this.DsPlataformaField;
            }
            set
            {
                this.DsPlataformaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutAtributoReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutAtributoReq : LogService.DataContractRequestExtension
    {

        private System.Nullable<long> IdAtributoField;

        private string DsAtributoField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Nullable<long> IdAtributo
        {
            get
            {
                return this.IdAtributoField;
            }
            set
            {
                this.IdAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string DsAtributo
        {
            get
            {
                return this.DsAtributoField;
            }
            set
            {
                this.DsAtributoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutTipoMensagemReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutTipoMensagemReq : LogService.DataContractRequestExtension
    {

        private System.Nullable<long> IdMensagemField;

        private string DsmensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Nullable<long> IdMensagem
        {
            get
            {
                return this.IdMensagemField;
            }
            set
            {
                this.IdMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Dsmensagem
        {
            get
            {
                return this.DsmensagemField;
            }
            set
            {
                this.DsmensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterPlataformaReq", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterPlataformaReq : LogService.DataContractRequestExtension
    {

        private string DsPlataformaField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DsPlataforma
        {
            get
            {
                return this.DsPlataformaField;
            }
            set
            {
                this.DsPlataformaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoMensagemConsulta", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum TipoMensagemConsulta : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alerta = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trace = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Todos = 3,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoMensagem", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum TipoMensagem : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alerta = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trace = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataContractResponseExtension", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.PlataformaLista))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterTipoMensagemResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.TipoMensagemLista))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterTipoAtributosResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.TipoAtributoLista))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterDadosLogResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.DadosLogLista))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.InclusaoLogResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ManutPlataformaResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ManutAtributoResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ManutTipoMensagemResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogService.ObterPlataformaResp))]
    public partial class DataContractResponseExtension : object
    {

        private LogService.ResponseExtension ExtensionField;

        private LogService.ResponseStatus StatusField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LogService.ResponseExtension Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public LogService.ResponseStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseExtension", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ResponseExtension : object
    {

        private string TokenField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlataformaLista", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class PlataformaLista : LogService.DataContractResponseExtension
    {

        private long IdPlataformaField;

        private string DsplataformaField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long IdPlataforma
        {
            get
            {
                return this.IdPlataformaField;
            }
            set
            {
                this.IdPlataformaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Dsplataforma
        {
            get
            {
                return this.DsplataformaField;
            }
            set
            {
                this.DsplataformaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterTipoMensagemResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoMensagemResp : LogService.DataContractResponseExtension
    {

        private System.Collections.Generic.List<LogService.TipoMensagemLista> ListaTipoMensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public System.Collections.Generic.List<LogService.TipoMensagemLista> ListaTipoMensagem
        {
            get
            {
                return this.ListaTipoMensagemField;
            }
            set
            {
                this.ListaTipoMensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoMensagemLista", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class TipoMensagemLista : LogService.DataContractResponseExtension
    {

        private long IdTipoMensagemField;

        private string DsTipoMensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long IdTipoMensagem
        {
            get
            {
                return this.IdTipoMensagemField;
            }
            set
            {
                this.IdTipoMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string DsTipoMensagem
        {
            get
            {
                return this.DsTipoMensagemField;
            }
            set
            {
                this.DsTipoMensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterTipoAtributosResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoAtributosResp : LogService.DataContractResponseExtension
    {

        private System.Collections.Generic.List<LogService.TipoAtributoLista> ListaTipoAtributoField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public System.Collections.Generic.List<LogService.TipoAtributoLista> ListaTipoAtributo
        {
            get
            {
                return this.ListaTipoAtributoField;
            }
            set
            {
                this.ListaTipoAtributoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoAtributoLista", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class TipoAtributoLista : LogService.DataContractResponseExtension
    {

        private long IdTipoAtributoField;

        private string DsTipoAtributoField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long IdTipoAtributo
        {
            get
            {
                return this.IdTipoAtributoField;
            }
            set
            {
                this.IdTipoAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string DsTipoAtributo
        {
            get
            {
                return this.DsTipoAtributoField;
            }
            set
            {
                this.DsTipoAtributoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterDadosLogResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterDadosLogResp : LogService.DataContractResponseExtension
    {

        private System.Collections.Generic.List<LogService.DadosLogLista> ListaDadosLogField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public System.Collections.Generic.List<LogService.DadosLogLista> ListaDadosLog
        {
            get
            {
                return this.ListaDadosLogField;
            }
            set
            {
                this.ListaDadosLogField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DadosLogLista", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class DadosLogLista : LogService.DataContractResponseExtension
    {

        private System.DateTime DtEventoField;

        private string DsFonteGeradoraField;

        private string DsMensagemField;

        private string DsPilhaField;

        private string DsUsuarioField;

        private long IdTipoAtributoField;

        private string DsTipoAtributoField;

        private string VlAtributoField;

        private string DsWcfServicoField;

        private long IdPlataformaField;

        private string DsPlataformaField;

        private long IdTipoMensagemField;

        private string DsTipoMensagemField;

        private long IdLogField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime DtEvento
        {
            get
            {
                return this.DtEventoField;
            }
            set
            {
                this.DtEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string DsFonteGeradora
        {
            get
            {
                return this.DsFonteGeradoraField;
            }
            set
            {
                this.DsFonteGeradoraField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string DsMensagem
        {
            get
            {
                return this.DsMensagemField;
            }
            set
            {
                this.DsMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string DsPilha
        {
            get
            {
                return this.DsPilhaField;
            }
            set
            {
                this.DsPilhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string DsUsuario
        {
            get
            {
                return this.DsUsuarioField;
            }
            set
            {
                this.DsUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public long IdTipoAtributo
        {
            get
            {
                return this.IdTipoAtributoField;
            }
            set
            {
                this.IdTipoAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string DsTipoAtributo
        {
            get
            {
                return this.DsTipoAtributoField;
            }
            set
            {
                this.DsTipoAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string VlAtributo
        {
            get
            {
                return this.VlAtributoField;
            }
            set
            {
                this.VlAtributoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string DsWcfServico
        {
            get
            {
                return this.DsWcfServicoField;
            }
            set
            {
                this.DsWcfServicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 9)]
        public long IdPlataforma
        {
            get
            {
                return this.IdPlataformaField;
            }
            set
            {
                this.IdPlataformaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string DsPlataforma
        {
            get
            {
                return this.DsPlataformaField;
            }
            set
            {
                this.DsPlataformaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public long IdTipoMensagem
        {
            get
            {
                return this.IdTipoMensagemField;
            }
            set
            {
                this.IdTipoMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 12)]
        public string DsTipoMensagem
        {
            get
            {
                return this.DsTipoMensagemField;
            }
            set
            {
                this.DsTipoMensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 13)]
        public long IdLog
        {
            get
            {
                return this.IdLogField;
            }
            set
            {
                this.IdLogField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InclusaoLogResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class InclusaoLogResp : LogService.DataContractResponseExtension
    {

        private LogService.StatusInclusaoLog ResultadoField;

        private string MensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public LogService.StatusInclusaoLog Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutPlataformaResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutPlataformaResp : LogService.DataContractResponseExtension
    {

        private LogService.ManutPlataformaStatus ResultadoField;

        private string MensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public LogService.ManutPlataformaStatus Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutAtributoResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutAtributoResp : LogService.DataContractResponseExtension
    {

        private LogService.ManutAtributoStatus ResultadoField;

        private string MensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public LogService.ManutAtributoStatus Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutTipoMensagemResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutTipoMensagemResp : LogService.DataContractResponseExtension
    {

        private LogService.ManutTipoMensagemStatus ResultadoField;

        private string MensagemField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public LogService.ManutTipoMensagemStatus Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObterPlataformaResp", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterPlataformaResp : LogService.DataContractResponseExtension
    {

        private System.Collections.Generic.List<LogService.PlataformaLista> ListaPlataformasField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public System.Collections.Generic.List<LogService.PlataformaLista> ListaPlataformas
        {
            get
            {
                return this.ListaPlataformasField;
            }
            set
            {
                this.ListaPlataformasField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseStatus", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum ResponseStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 2,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StatusInclusaoLog", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum StatusInclusaoLog : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutPlataformaStatus", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum ManutPlataformaStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutAtributoStatus", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum ManutAtributoStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ManutTipoMensagemStatus", Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public enum ManutTipoMensagemStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
    public partial class ServiceFaultException : object
    {

        private string InformationField;

        private string TraceResultField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information
        {
            get
            {
                return this.InformationField;
            }
            set
            {
                this.InformationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraceResult
        {
            get
            {
                return this.TraceResultField;
            }
            set
            {
                this.TraceResultField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus", ConfigurationName = "LogService.ILog")]
    public interface ILog
    {

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ObterPlataforma", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterPlataformaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterPlataformaServiceFaultExceptionFaul" +
            "t", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ObterPlataformaResponse ObterPlataforma(LogService.ObterPlataformaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ObterPlataforma", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterPlataformaResponse")]
        System.Threading.Tasks.Task<LogService.ObterPlataformaResponse> ObterPlataformaAsync(LogService.ObterPlataformaRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ObterTipoMensagem", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterTipoMensagemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterTipoMensagemServiceFaultExceptionFa" +
            "ult", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ObterTipoMensagemResponse ObterTipoMensagem(LogService.ObterTipoMensagemRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ObterTipoMensagem", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterTipoMensagemResponse")]
        System.Threading.Tasks.Task<LogService.ObterTipoMensagemResponse> ObterTipoMensagemAsync(LogService.ObterTipoMensagemRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ObterTipoAtributo", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterTipoAtributoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterTipoAtributoServiceFaultExceptionFa" +
            "ult", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ObterTipoAtributoResponse ObterTipoAtributo(LogService.ObterTipoAtributoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ObterTipoAtributo", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterTipoAtributoResponse")]
        System.Threading.Tasks.Task<LogService.ObterTipoAtributoResponse> ObterTipoAtributoAsync(LogService.ObterTipoAtributoRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ObterLogMensagem", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterLogMensagemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterLogMensagemServiceFaultExceptionFau" +
            "lt", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ObterLogMensagemResponse ObterLogMensagem(LogService.ObterLogMensagemRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ObterLogMensagem", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ObterLogMensagemResponse")]
        System.Threading.Tasks.Task<LogService.ObterLogMensagemResponse> ObterLogMensagemAsync(LogService.ObterLogMensagemRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "IncluirLog", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/IncluirLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/IncluirLogServiceFaultExceptionFault", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.IncluirLogResponse IncluirLog(LogService.IncluirLogRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "IncluirLog", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/IncluirLogResponse")]
        System.Threading.Tasks.Task<LogService.IncluirLogResponse> IncluirLogAsync(LogService.IncluirLogRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ManutencaoDadosPlataforma", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosPlataformaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosPlataformaServiceFaultExc" +
            "eptionFault", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ManutencaoDadosPlataformaResponse ManutencaoDadosPlataforma(LogService.ManutencaoDadosPlataformaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ManutencaoDadosPlataforma", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosPlataformaResponse")]
        System.Threading.Tasks.Task<LogService.ManutencaoDadosPlataformaResponse> ManutencaoDadosPlataformaAsync(LogService.ManutencaoDadosPlataformaRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ManutencaoDadosTipoAtributo", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosTipoAtributoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosTipoAtributoServiceFaultE" +
            "xceptionFault", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ManutencaoDadosTipoAtributoResponse ManutencaoDadosTipoAtributo(LogService.ManutencaoDadosTipoAtributoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ManutencaoDadosTipoAtributo", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosTipoAtributoResponse")]
        System.Threading.Tasks.Task<LogService.ManutencaoDadosTipoAtributoResponse> ManutencaoDadosTipoAtributoAsync(LogService.ManutencaoDadosTipoAtributoRequest request);

        // CODEGEN: Generating message contract since element name req from namespace http://www.Vwfsbr.com.br/servicebus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "ManutencaoDadosTipoMensagem", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosTipoMensagemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogService.ServiceFaultException), Action = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosTipoMensagemServiceFaultE" +
            "xceptionFault", Name = "ServiceFaultException", Namespace = "http://schemas.datacontract.org/2004/07/Vwfsbr.InfraServiceBus.Exceptions")]
        LogService.ManutencaoDadosTipoMensagemResponse ManutencaoDadosTipoMensagem(LogService.ManutencaoDadosTipoMensagemRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ManutencaoDadosTipoMensagem", ReplyAction = "http://www.Vwfsbr.com.br/servicebus/ILog/ManutencaoDadosTipoMensagemResponse")]
        System.Threading.Tasks.Task<LogService.ManutencaoDadosTipoMensagemResponse> ManutencaoDadosTipoMensagemAsync(LogService.ManutencaoDadosTipoMensagemRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterPlataformaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterPlataforma", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterPlataformaRequestBody Body;

        public ObterPlataformaRequest()
        {
        }

        public ObterPlataformaRequest(LogService.ObterPlataformaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterPlataformaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterPlataformaReq req;

        public ObterPlataformaRequestBody()
        {
        }

        public ObterPlataformaRequestBody(LogService.ObterPlataformaReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterPlataformaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterPlataformaResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterPlataformaResponseBody Body;

        public ObterPlataformaResponse()
        {
        }

        public ObterPlataformaResponse(LogService.ObterPlataformaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterPlataformaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterPlataformaResp ObterPlataformaResult;

        public ObterPlataformaResponseBody()
        {
        }

        public ObterPlataformaResponseBody(LogService.ObterPlataformaResp ObterPlataformaResult)
        {
            this.ObterPlataformaResult = ObterPlataformaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterTipoMensagemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterTipoMensagem", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterTipoMensagemRequestBody Body;

        public ObterTipoMensagemRequest()
        {
        }

        public ObterTipoMensagemRequest(LogService.ObterTipoMensagemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoMensagemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterTipoMensagemReq req;

        public ObterTipoMensagemRequestBody()
        {
        }

        public ObterTipoMensagemRequestBody(LogService.ObterTipoMensagemReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterTipoMensagemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterTipoMensagemResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterTipoMensagemResponseBody Body;

        public ObterTipoMensagemResponse()
        {
        }

        public ObterTipoMensagemResponse(LogService.ObterTipoMensagemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoMensagemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterTipoMensagemResp ObterTipoMensagemResult;

        public ObterTipoMensagemResponseBody()
        {
        }

        public ObterTipoMensagemResponseBody(LogService.ObterTipoMensagemResp ObterTipoMensagemResult)
        {
            this.ObterTipoMensagemResult = ObterTipoMensagemResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterTipoAtributoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterTipoAtributo", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterTipoAtributoRequestBody Body;

        public ObterTipoAtributoRequest()
        {
        }

        public ObterTipoAtributoRequest(LogService.ObterTipoAtributoRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoAtributoRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterTipoAtributosReq req;

        public ObterTipoAtributoRequestBody()
        {
        }

        public ObterTipoAtributoRequestBody(LogService.ObterTipoAtributosReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterTipoAtributoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterTipoAtributoResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterTipoAtributoResponseBody Body;

        public ObterTipoAtributoResponse()
        {
        }

        public ObterTipoAtributoResponse(LogService.ObterTipoAtributoResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterTipoAtributoResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterTipoAtributosResp ObterTipoAtributoResult;

        public ObterTipoAtributoResponseBody()
        {
        }

        public ObterTipoAtributoResponseBody(LogService.ObterTipoAtributosResp ObterTipoAtributoResult)
        {
            this.ObterTipoAtributoResult = ObterTipoAtributoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterLogMensagemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterLogMensagem", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterLogMensagemRequestBody Body;

        public ObterLogMensagemRequest()
        {
        }

        public ObterLogMensagemRequest(LogService.ObterLogMensagemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterLogMensagemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterDadosLogReq req;

        public ObterLogMensagemRequestBody()
        {
        }

        public ObterLogMensagemRequestBody(LogService.ObterDadosLogReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ObterLogMensagemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ObterLogMensagemResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ObterLogMensagemResponseBody Body;

        public ObterLogMensagemResponse()
        {
        }

        public ObterLogMensagemResponse(LogService.ObterLogMensagemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ObterLogMensagemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ObterDadosLogResp ObterLogMensagemResult;

        public ObterLogMensagemResponseBody()
        {
        }

        public ObterLogMensagemResponseBody(LogService.ObterDadosLogResp ObterLogMensagemResult)
        {
            this.ObterLogMensagemResult = ObterLogMensagemResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IncluirLogRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "IncluirLog", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.IncluirLogRequestBody Body;

        public IncluirLogRequest()
        {
        }

        public IncluirLogRequest(LogService.IncluirLogRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class IncluirLogRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.InclusaoLogReq req;

        public IncluirLogRequestBody()
        {
        }

        public IncluirLogRequestBody(LogService.InclusaoLogReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IncluirLogResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "IncluirLogResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.IncluirLogResponseBody Body;

        public IncluirLogResponse()
        {
        }

        public IncluirLogResponse(LogService.IncluirLogResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class IncluirLogResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.InclusaoLogResp IncluirLogResult;

        public IncluirLogResponseBody()
        {
        }

        public IncluirLogResponseBody(LogService.InclusaoLogResp IncluirLogResult)
        {
            this.IncluirLogResult = IncluirLogResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ManutencaoDadosPlataformaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ManutencaoDadosPlataforma", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ManutencaoDadosPlataformaRequestBody Body;

        public ManutencaoDadosPlataformaRequest()
        {
        }

        public ManutencaoDadosPlataformaRequest(LogService.ManutencaoDadosPlataformaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutencaoDadosPlataformaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ManutPlataformaReq req;

        public ManutencaoDadosPlataformaRequestBody()
        {
        }

        public ManutencaoDadosPlataformaRequestBody(LogService.ManutPlataformaReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ManutencaoDadosPlataformaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ManutencaoDadosPlataformaResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ManutencaoDadosPlataformaResponseBody Body;

        public ManutencaoDadosPlataformaResponse()
        {
        }

        public ManutencaoDadosPlataformaResponse(LogService.ManutencaoDadosPlataformaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutencaoDadosPlataformaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ManutPlataformaResp ManutencaoDadosPlataformaResult;

        public ManutencaoDadosPlataformaResponseBody()
        {
        }

        public ManutencaoDadosPlataformaResponseBody(LogService.ManutPlataformaResp ManutencaoDadosPlataformaResult)
        {
            this.ManutencaoDadosPlataformaResult = ManutencaoDadosPlataformaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ManutencaoDadosTipoAtributoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ManutencaoDadosTipoAtributo", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ManutencaoDadosTipoAtributoRequestBody Body;

        public ManutencaoDadosTipoAtributoRequest()
        {
        }

        public ManutencaoDadosTipoAtributoRequest(LogService.ManutencaoDadosTipoAtributoRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutencaoDadosTipoAtributoRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ManutAtributoReq req;

        public ManutencaoDadosTipoAtributoRequestBody()
        {
        }

        public ManutencaoDadosTipoAtributoRequestBody(LogService.ManutAtributoReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ManutencaoDadosTipoAtributoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ManutencaoDadosTipoAtributoResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ManutencaoDadosTipoAtributoResponseBody Body;

        public ManutencaoDadosTipoAtributoResponse()
        {
        }

        public ManutencaoDadosTipoAtributoResponse(LogService.ManutencaoDadosTipoAtributoResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutencaoDadosTipoAtributoResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ManutAtributoResp ManutencaoDadosTipoAtributoResult;

        public ManutencaoDadosTipoAtributoResponseBody()
        {
        }

        public ManutencaoDadosTipoAtributoResponseBody(LogService.ManutAtributoResp ManutencaoDadosTipoAtributoResult)
        {
            this.ManutencaoDadosTipoAtributoResult = ManutencaoDadosTipoAtributoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ManutencaoDadosTipoMensagemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ManutencaoDadosTipoMensagem", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ManutencaoDadosTipoMensagemRequestBody Body;

        public ManutencaoDadosTipoMensagemRequest()
        {
        }

        public ManutencaoDadosTipoMensagemRequest(LogService.ManutencaoDadosTipoMensagemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutencaoDadosTipoMensagemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ManutTipoMensagemReq req;

        public ManutencaoDadosTipoMensagemRequestBody()
        {
        }

        public ManutencaoDadosTipoMensagemRequestBody(LogService.ManutTipoMensagemReq req)
        {
            this.req = req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ManutencaoDadosTipoMensagemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ManutencaoDadosTipoMensagemResponse", Namespace = "http://www.Vwfsbr.com.br/servicebus", Order = 0)]
        public LogService.ManutencaoDadosTipoMensagemResponseBody Body;

        public ManutencaoDadosTipoMensagemResponse()
        {
        }

        public ManutencaoDadosTipoMensagemResponse(LogService.ManutencaoDadosTipoMensagemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.Vwfsbr.com.br/servicebus")]
    public partial class ManutencaoDadosTipoMensagemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LogService.ManutTipoMensagemResp ManutencaoDadosTipoMensagemResult;

        public ManutencaoDadosTipoMensagemResponseBody()
        {
        }

        public ManutencaoDadosTipoMensagemResponseBody(LogService.ManutTipoMensagemResp ManutencaoDadosTipoMensagemResult)
        {
            this.ManutencaoDadosTipoMensagemResult = ManutencaoDadosTipoMensagemResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ILogChannel : LogService.ILog, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LogClient : System.ServiceModel.ClientBase<LogService.ILog>, LogService.ILog
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public LogClient() :
                base(LogClient.GetDefaultBinding(), LogClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LogSvcHTTP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LogClient(EndpointConfiguration endpointConfiguration) :
                base(LogClient.GetBindingForEndpoint(endpointConfiguration), LogClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LogClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(LogClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LogClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(LogClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ObterPlataformaResponse LogService.ILog.ObterPlataforma(LogService.ObterPlataformaRequest request)
        {
            return base.Channel.ObterPlataforma(request);
        }

        public LogService.ObterPlataformaResp ObterPlataforma(LogService.ObterPlataformaReq req)
        {
            LogService.ObterPlataformaRequest inValue = new LogService.ObterPlataformaRequest();
            inValue.Body = new LogService.ObterPlataformaRequestBody();
            inValue.Body.req = req;
            LogService.ObterPlataformaResponse retVal = ((LogService.ILog)(this)).ObterPlataforma(inValue);
            return retVal.Body.ObterPlataformaResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ObterPlataformaResponse> LogService.ILog.ObterPlataformaAsync(LogService.ObterPlataformaRequest request)
        {
            return base.Channel.ObterPlataformaAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ObterPlataformaResponse> ObterPlataformaAsync(LogService.ObterPlataformaReq req)
        {
            LogService.ObterPlataformaRequest inValue = new LogService.ObterPlataformaRequest();
            inValue.Body = new LogService.ObterPlataformaRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ObterPlataformaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ObterTipoMensagemResponse LogService.ILog.ObterTipoMensagem(LogService.ObterTipoMensagemRequest request)
        {
            return base.Channel.ObterTipoMensagem(request);
        }

        public LogService.ObterTipoMensagemResp ObterTipoMensagem(LogService.ObterTipoMensagemReq req)
        {
            LogService.ObterTipoMensagemRequest inValue = new LogService.ObterTipoMensagemRequest();
            inValue.Body = new LogService.ObterTipoMensagemRequestBody();
            inValue.Body.req = req;
            LogService.ObterTipoMensagemResponse retVal = ((LogService.ILog)(this)).ObterTipoMensagem(inValue);
            return retVal.Body.ObterTipoMensagemResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ObterTipoMensagemResponse> LogService.ILog.ObterTipoMensagemAsync(LogService.ObterTipoMensagemRequest request)
        {
            return base.Channel.ObterTipoMensagemAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ObterTipoMensagemResponse> ObterTipoMensagemAsync(LogService.ObterTipoMensagemReq req)
        {
            LogService.ObterTipoMensagemRequest inValue = new LogService.ObterTipoMensagemRequest();
            inValue.Body = new LogService.ObterTipoMensagemRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ObterTipoMensagemAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ObterTipoAtributoResponse LogService.ILog.ObterTipoAtributo(LogService.ObterTipoAtributoRequest request)
        {
            return base.Channel.ObterTipoAtributo(request);
        }

        public LogService.ObterTipoAtributosResp ObterTipoAtributo(LogService.ObterTipoAtributosReq req)
        {
            LogService.ObterTipoAtributoRequest inValue = new LogService.ObterTipoAtributoRequest();
            inValue.Body = new LogService.ObterTipoAtributoRequestBody();
            inValue.Body.req = req;
            LogService.ObterTipoAtributoResponse retVal = ((LogService.ILog)(this)).ObterTipoAtributo(inValue);
            return retVal.Body.ObterTipoAtributoResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ObterTipoAtributoResponse> LogService.ILog.ObterTipoAtributoAsync(LogService.ObterTipoAtributoRequest request)
        {
            return base.Channel.ObterTipoAtributoAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ObterTipoAtributoResponse> ObterTipoAtributoAsync(LogService.ObterTipoAtributosReq req)
        {
            LogService.ObterTipoAtributoRequest inValue = new LogService.ObterTipoAtributoRequest();
            inValue.Body = new LogService.ObterTipoAtributoRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ObterTipoAtributoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ObterLogMensagemResponse LogService.ILog.ObterLogMensagem(LogService.ObterLogMensagemRequest request)
        {
            return base.Channel.ObterLogMensagem(request);
        }

        public LogService.ObterDadosLogResp ObterLogMensagem(LogService.ObterDadosLogReq req)
        {
            LogService.ObterLogMensagemRequest inValue = new LogService.ObterLogMensagemRequest();
            inValue.Body = new LogService.ObterLogMensagemRequestBody();
            inValue.Body.req = req;
            LogService.ObterLogMensagemResponse retVal = ((LogService.ILog)(this)).ObterLogMensagem(inValue);
            return retVal.Body.ObterLogMensagemResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ObterLogMensagemResponse> LogService.ILog.ObterLogMensagemAsync(LogService.ObterLogMensagemRequest request)
        {
            return base.Channel.ObterLogMensagemAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ObterLogMensagemResponse> ObterLogMensagemAsync(LogService.ObterDadosLogReq req)
        {
            LogService.ObterLogMensagemRequest inValue = new LogService.ObterLogMensagemRequest();
            inValue.Body = new LogService.ObterLogMensagemRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ObterLogMensagemAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.IncluirLogResponse LogService.ILog.IncluirLog(LogService.IncluirLogRequest request)
        {
            return base.Channel.IncluirLog(request);
        }

        public LogService.InclusaoLogResp IncluirLog(LogService.InclusaoLogReq req)
        {
            LogService.IncluirLogRequest inValue = new LogService.IncluirLogRequest();
            inValue.Body = new LogService.IncluirLogRequestBody();
            inValue.Body.req = req;
            LogService.IncluirLogResponse retVal = ((LogService.ILog)(this)).IncluirLog(inValue);
            return retVal.Body.IncluirLogResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.IncluirLogResponse> LogService.ILog.IncluirLogAsync(LogService.IncluirLogRequest request)
        {
            return base.Channel.IncluirLogAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.IncluirLogResponse> IncluirLogAsync(LogService.InclusaoLogReq req)
        {
            LogService.IncluirLogRequest inValue = new LogService.IncluirLogRequest();
            inValue.Body = new LogService.IncluirLogRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).IncluirLogAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ManutencaoDadosPlataformaResponse LogService.ILog.ManutencaoDadosPlataforma(LogService.ManutencaoDadosPlataformaRequest request)
        {
            return base.Channel.ManutencaoDadosPlataforma(request);
        }

        public LogService.ManutPlataformaResp ManutencaoDadosPlataforma(LogService.ManutPlataformaReq req)
        {
            LogService.ManutencaoDadosPlataformaRequest inValue = new LogService.ManutencaoDadosPlataformaRequest();
            inValue.Body = new LogService.ManutencaoDadosPlataformaRequestBody();
            inValue.Body.req = req;
            LogService.ManutencaoDadosPlataformaResponse retVal = ((LogService.ILog)(this)).ManutencaoDadosPlataforma(inValue);
            return retVal.Body.ManutencaoDadosPlataformaResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ManutencaoDadosPlataformaResponse> LogService.ILog.ManutencaoDadosPlataformaAsync(LogService.ManutencaoDadosPlataformaRequest request)
        {
            return base.Channel.ManutencaoDadosPlataformaAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ManutencaoDadosPlataformaResponse> ManutencaoDadosPlataformaAsync(LogService.ManutPlataformaReq req)
        {
            LogService.ManutencaoDadosPlataformaRequest inValue = new LogService.ManutencaoDadosPlataformaRequest();
            inValue.Body = new LogService.ManutencaoDadosPlataformaRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ManutencaoDadosPlataformaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ManutencaoDadosTipoAtributoResponse LogService.ILog.ManutencaoDadosTipoAtributo(LogService.ManutencaoDadosTipoAtributoRequest request)
        {
            return base.Channel.ManutencaoDadosTipoAtributo(request);
        }

        public LogService.ManutAtributoResp ManutencaoDadosTipoAtributo(LogService.ManutAtributoReq req)
        {
            LogService.ManutencaoDadosTipoAtributoRequest inValue = new LogService.ManutencaoDadosTipoAtributoRequest();
            inValue.Body = new LogService.ManutencaoDadosTipoAtributoRequestBody();
            inValue.Body.req = req;
            LogService.ManutencaoDadosTipoAtributoResponse retVal = ((LogService.ILog)(this)).ManutencaoDadosTipoAtributo(inValue);
            return retVal.Body.ManutencaoDadosTipoAtributoResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ManutencaoDadosTipoAtributoResponse> LogService.ILog.ManutencaoDadosTipoAtributoAsync(LogService.ManutencaoDadosTipoAtributoRequest request)
        {
            return base.Channel.ManutencaoDadosTipoAtributoAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ManutencaoDadosTipoAtributoResponse> ManutencaoDadosTipoAtributoAsync(LogService.ManutAtributoReq req)
        {
            LogService.ManutencaoDadosTipoAtributoRequest inValue = new LogService.ManutencaoDadosTipoAtributoRequest();
            inValue.Body = new LogService.ManutencaoDadosTipoAtributoRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ManutencaoDadosTipoAtributoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogService.ManutencaoDadosTipoMensagemResponse LogService.ILog.ManutencaoDadosTipoMensagem(LogService.ManutencaoDadosTipoMensagemRequest request)
        {
            return base.Channel.ManutencaoDadosTipoMensagem(request);
        }

        public LogService.ManutTipoMensagemResp ManutencaoDadosTipoMensagem(LogService.ManutTipoMensagemReq req)
        {
            LogService.ManutencaoDadosTipoMensagemRequest inValue = new LogService.ManutencaoDadosTipoMensagemRequest();
            inValue.Body = new LogService.ManutencaoDadosTipoMensagemRequestBody();
            inValue.Body.req = req;
            LogService.ManutencaoDadosTipoMensagemResponse retVal = ((LogService.ILog)(this)).ManutencaoDadosTipoMensagem(inValue);
            return retVal.Body.ManutencaoDadosTipoMensagemResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogService.ManutencaoDadosTipoMensagemResponse> LogService.ILog.ManutencaoDadosTipoMensagemAsync(LogService.ManutencaoDadosTipoMensagemRequest request)
        {
            return base.Channel.ManutencaoDadosTipoMensagemAsync(request);
        }

        public System.Threading.Tasks.Task<LogService.ManutencaoDadosTipoMensagemResponse> ManutencaoDadosTipoMensagemAsync(LogService.ManutTipoMensagemReq req)
        {
            LogService.ManutencaoDadosTipoMensagemRequest inValue = new LogService.ManutencaoDadosTipoMensagemRequest();
            inValue.Body = new LogService.ManutencaoDadosTipoMensagemRequestBody();
            inValue.Body.req = req;
            return ((LogService.ILog)(this)).ManutencaoDadosTipoMensagemAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LogSvcHTTP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LogSvcHTTP))
            {
                return new System.ServiceModel.EndpointAddress("http://integration-dev/LogSvc/LogService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LogClient.GetBindingForEndpoint(EndpointConfiguration.LogSvcHTTP);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LogClient.GetEndpointAddress(EndpointConfiguration.LogSvcHTTP);
        }

        public enum EndpointConfiguration
        {

            LogSvcHTTP,
        }
    }
}
